### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by haozidede** [jwehrmann/retrieval.pytorch#5]
Hi jwehrmann,
I have followed the README.md to reproduce the experiments.
However, the caption data "train_caps.en.txt" could not be found in the SCAN provided dataset.
There is just "train_caps.txt". Does you miss it, or Should I rename the file?
 Thank you very much.

**Comment by jwehrmann** [comment]
They are the same file, you can simply rename it to train_caps.en.txt.
